apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: api-codecov-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-codecov-demo
    app.kubernetes.io/part-of: codecov-demo
  name: api-codecov-demohqv6
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: api-codecov-demo
    weight: null
status: {}
