apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: api-codecov-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-codecov-demo
    app.kubernetes.io/part-of: codecov-demo
  name: api-codecov-demo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: api-codecov-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: api-codecov-demo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/xjiang-tenant/codecov-demo/api-codecov-demo@sha256:2ea2dbac2cb601d3eb70b1f5504082914cfeee2402bcebe786d042d3755c271f
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
